
# spring.sql.init.data-locations=classpath:db/data/data-dev.sql 
# spring.jpa.properties.hibernate.jdbc.time_zone=UTC 
# logging.pattern.console=%d{HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n


server:
  port: 8080

  # override springboot whitepage /resources/template
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    default: dev

  application:
    name: bookmark-web-api

  sql:
    init:
      mode: never

  h2:
    console:
      enabled: true

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          

